# Task 1. Working with images as matrices

## Обробка зображення: 3×3 матриця

Дано матрицю зображення \(M\) та матрицю ефекту \(E\):

$$
M =
\begin{bmatrix}
100 & 150 & 200 \\
50 & 100 & 150 \\
0 & 50 & 100
\end{bmatrix}, \quad
E =
\begin{bmatrix}
20 & 30 & 40 \\
10 & 20 & 30 \\
5 & 10 & 15
\end{bmatrix}
$$

### 1. Зменшення контрасту
Множимо кожен елемент матриці $M$ на скаляр $\lambda = 0.5$:

$$
M_{\text{contrast}} = 0.5 \cdot M =
\begin{bmatrix}
50 & 75 & 100 \\
25 & 50 & 75 \\
0 & 25 & 50
\end{bmatrix}
$$

### 2. Корекція яскравості
Додаємо скаляр \(c = 25\) до кожного елемента матриці \(M\):

$$
M_{\text{brightness}} = M + 25 =
\begin{bmatrix}
125 & 175 & 225 \\
75 & 125 & 175 \\
25 & 75 & 125
\end{bmatrix}
$$

### 3. Змішування (Blending)
Лінійна комбінація оригіналу та ефекту:

$$
M_{\text{blend}} = 0.8 \cdot M + 0.2 \cdot E =
\begin{bmatrix}
84 & 126 & 168 \\
42 & 84 & 126 \\
1 & 42 & 83
\end{bmatrix}
$$

In [17]:
import numpy as np

# Matrices
M = np.array([
    [100, 150, 200],
    [50, 100, 150],
    [0, 50, 100]
])

E = np.array([
    [20, 30, 40],
    [10, 20, 30],
    [5, 10, 15],
])

print("Matrice M:")
print(M)
print("\nMatrice E:")
print(E)

# Change the contrast
lambda_ = 0.5
M_contrast = (lambda_ * M).astype(int) #remove dots
print("\n1. Change the contrast: M_contrast = λ * M")
print(M_contrast)

#Brightness correction
c = 25
M_bright = (c + M).astype(int)
print("\n2. Brightness correction: M_bright = c + M")
print(M_bright)

# Blending
M_blend= (0.8*M + 0.2*E).astype(int)
print("\n3. Blending:")
print(M_blend)



Matrice M:
[[100 150 200]
 [ 50 100 150]
 [  0  50 100]]

Matrice E:
[[20 30 40]
 [10 20 30]
 [ 5 10 15]]

1. Change the contrast: M_contrast = λ * M
[[ 50  75 100]
 [ 25  50  75]
 [  0  25  50]]

2. Brightness correction: M_bright = c + M
[[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]

3. Blending:
[[ 84 126 168]
 [ 42  84 126]
 [  1  42  83]]


# Task 2. Search for similar movies

## Рекомендаційні системи: Косинусна схожість

Маємо вектори інтересів користувача та трьох фільмів:

$$
\mathbf{u} =
\begin{bmatrix} 8 \\ 2 \\ 5 \end{bmatrix}, \quad
\mathbf{v}_A =
\begin{bmatrix} 9 \\ 1 \\ 2 \end{bmatrix}, \quad
\mathbf{v}_B =
\begin{bmatrix} 1 \\ 9 \\ 8 \end{bmatrix}, \quad
\mathbf{v}_C =
\begin{bmatrix} 7 \\ 2 \\ 6 \end{bmatrix}
$$

---

### 1. Норма вектора користувача

$$
\|\mathbf{u}\| = \sqrt{8^2 + 2^2 + 5^2}
= \sqrt{64 + 4 + 25}
= \sqrt{93} \approx 9.644
$$

---

### 2. Косинусна схожість

Формула:

$$
\cos \theta = \frac{\mathbf{u} \cdot \mathbf{v}}{\|\mathbf{u}\| \, \|\mathbf{v}\|}, \quad
\mathbf{u} \cdot \mathbf{v} = \sum_i u_i v_i
$$

#### Фільм A:

$$
\mathbf{u} \cdot \mathbf{v}_A = 8\cdot 9 + 2\cdot 1 + 5\cdot 2 = 84
$$

$$
\|\mathbf{v}_A\| = \sqrt{9^2 + 1^2 + 2^2} = \sqrt{86} \approx 9.274
$$

$$
\cos \theta_A = \frac{84}{9.644 \cdot 9.274} \approx 0.939
$$

#### Фільм B:

$$
\mathbf{u} \cdot \mathbf{v}_B = 8\cdot 1 + 2\cdot 9 + 5\cdot 8 = 66
$$

$$
\|\mathbf{v}_B\| = \sqrt{1^2 + 9^2 + 8^2} = \sqrt{146} \approx 12.083
$$

$$
\cos \theta_B = \frac{66}{9.644 \cdot 12.083} \approx 0.567
$$

#### Фільм C:

$$
\mathbf{u} \cdot \mathbf{v}_C = 8\cdot 7 + 2\cdot 2 + 5\cdot 6 = 90
$$

$$
\|\mathbf{v}_C\| = \sqrt{7^2 + 2^2 + 6^2} = \sqrt{89} \approx 9.434
$$

$$
\cos \theta_C = \frac{90}{9.644 \cdot 9.434} \approx 0.990
$$

---

### 3. Висновок

Косинусні схожості:

$$
\cos \theta_A \approx 0.939, \quad
\cos \theta_B \approx 0.567, \quad
\cos \theta_C \approx 0.990
$$

**Фільм C найбільше підходить користувачу!**

In [21]:
import numpy as np

u = np.array([8, 2, 5])

v_a = np.array([9, 1, 2])
v_b = np.array([1, 9, 8])
v_c = np.array([7, 2, 6])

# norm for u
normU_L2 = np.linalg.norm(u)
print("User vector u:", u)
print("||u|| =", round(normU_L2, 3))

# ===== Case A =====
dotA_product = u @ v_a
normA_L2 = np.linalg.norm(v_a)
cos_theta_A = dotA_product / (normU_L2 * normA_L2)

print("\n--- Movie A ---")
print("v_A:", v_a)
print("u · v_A =", dotA_product)
print("||v_A|| =", round(normA_L2, 3))
print("cos(theta_A) =", round(cos_theta_A, 3))

# ===== Case B =====
dotB_product = u @ v_b
normB_L2 = np.linalg.norm(v_b)
cos_theta_B = dotB_product / (normU_L2 * normB_L2)

print("\n--- Movie B ---")
print("v_B:", v_b)
print("u · v_B =", dotB_product)
print("||v_B|| =", round(normB_L2, 3))
print("cos(theta_B) =", round(cos_theta_B, 3))

# ===== Case C =====
dotC_product = u @ v_c
normC_L2 = np.linalg.norm(v_c)
cos_theta_C = dotC_product / (normU_L2 * normC_L2)  # FIXED HERE

print("\n--- Movie C ---")
print("v_C:", v_c)
print("u · v_C =", dotC_product)
print("||v_C|| =", round(normC_L2, 3))
print("cos(theta_C) =", round(cos_theta_C, 3))

# ===== Final decision =====
print("\n--- Result ---")
print("A:", round(cos_theta_A, 3))
print("B:", round(cos_theta_B, 3))
print("C:", round(cos_theta_C, 3))

best = max({
    "A": cos_theta_A,
    "B": cos_theta_B,
    "C": cos_theta_C
}, key=lambda x: {
    "A": cos_theta_A,
    "B": cos_theta_B,
    "C": cos_theta_C
}[x])

print("Best match:", best)

User vector u: [8 2 5]
||u|| = 9.644

--- Movie A ---
v_A: [9 1 2]
u · v_A = 84
||v_A|| = 9.274
cos(theta_A) = 0.939

--- Movie B ---
v_B: [1 9 8]
u · v_B = 66
||v_B|| = 12.083
cos(theta_B) = 0.566

--- Movie C ---
v_C: [7 2 6]
u · v_C = 90
||v_C|| = 9.434
cos(theta_C) = 0.989

--- Result ---
A: 0.939
B: 0.566
C: 0.989
Best match: C


# Task 3. Production analysis

## Розв’язання системи лінійних рівнянь: виробництво дронів

Маємо систему:

$$
A \mathbf{x} = \mathbf{b}
$$

---

### 1. Формування матриці та вектора

Матриця витрат ресурсів:

$$
A =
\begin{bmatrix}
4 & 4 & 6 \\
1 & 1 & 2 \\
1 & 2 & 4
\end{bmatrix}
$$

де стовпці відповідають дронам:
- Розвідник
- Камікадзе
- Вантажний

Вектор загальних витрат:

$$
\mathbf{b} =
\begin{bmatrix}
460 \\
130 \\
240
\end{bmatrix}
$$

---

### 2. Перевірка існування розв’язку

Обчислюємо визначник:

$$
\det(A) =
\begin{vmatrix}
4 & 4 & 6 \\
1 & 1 & 2 \\
1 & 2 & 4
\end{vmatrix}
$$

Розкладемо по першому рядку:

$$
= 4
\begin{vmatrix}
1 & 2 \\
2 & 4
\end{vmatrix}
- 4
\begin{vmatrix}
1 & 2 \\
1 & 4
\end{vmatrix}
+ 6
\begin{vmatrix}
1 & 1 \\
1 & 2
\end{vmatrix}
$$

$$
= 4(1\cdot4 - 2\cdot2) - 4(1\cdot4 - 2\cdot1) + 6(1\cdot2 - 1\cdot1)
$$

$$
= 4(4 - 4) - 4(4 - 2) + 6(2 - 1)
$$

$$
= 0 - 8 + 6 = -2
$$

$$
\det(A) \ne 0 \Rightarrow \text{система має єдиний розв’язок}
$$

---

### 3. Розв’язання системи

Розв’язок:

$$
\mathbf{x} =
\begin{bmatrix}
50 \\
30 \\
20
\end{bmatrix}
$$

---

### 4. Перевірка

Перемножимо:

$$
A \mathbf{x} =
\begin{bmatrix}
4 & 4 & 6 \\
1 & 1 & 2 \\
1 & 2 & 4
\end{bmatrix}
\begin{bmatrix}
50 \\
30 \\
20
\end{bmatrix}
=
\begin{bmatrix}
460 \\
130 \\
240
\end{bmatrix}
= \mathbf{b}
$$

---

### 5. Висновок

Було зібрано:

- **50** розвідувальних дронів  
- **30** дронів-камікадзе  
- **20** вантажних дронів  

$$
\boxed{\text{Розв’язок підтверджено}}
$$

In [26]:
import numpy as np

# Matrix A (resources per drone type)
A = np.array([
    [4, 4, 6],  # motors
    [1, 1, 2],  # controllers
    [1, 2, 4]   # batteries
])

# Vector b (total resources used)
b = np.array([460, 130, 240])

print("Matrix A:")
print(A)

print("\nVector b:")
print(b)


# 1. Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:", round(det_A, 3))

if det_A != 0:
    print("System has a unique solution ✅")
else:
    print("System has NO unique solution ❌")


# 2. Solve system
x_solution = np.linalg.solve(A, b)

print("\nSolution vector x:")
print("[Scout, Kamikaze, Cargo]")
print(x_solution.astype(int))


# 3. Check
check = A @ x_solution

print("\nCheck: A * x =")
print(check.astype(int))

print("\nOriginal b =")
print(b)


# 4. Final interpretation
print("\n--- Result ---")
print("Scout drones:", int(x_solution[0]))
print("Kamikaze drones:", int(x_solution[1]))
print("Cargo drones:", int(x_solution[2]))

Matrix A:
[[4 4 6]
 [1 1 2]
 [1 2 4]]

Vector b:
[460 130 240]

Determinant of A: -2.0
System has a unique solution ✅

Solution vector x:
[Scout, Kamikaze, Cargo]
[20 50 30]

Check: A * x =
[460 130 240]

Original b =
[460 130 240]

--- Result ---
Scout drones: 20
Kamikaze drones: 50
Cargo drones: 30


# Task 4. Trend forecast

## Лінійна регресія: метод найменших квадратів

Маємо дані:

$$
t = [1, 2, 3, 4, 5], \quad
y = [22, 28, 37, 45, 53]
$$

Потрібно знайти рівняння прямої:

$$
y = k t + b
$$

---

### 1. Формування матриці \(A\)

$$
A =
\begin{bmatrix}
1 & 1 \\
2 & 1 \\
3 & 1 \\
4 & 1 \\
5 & 1
\end{bmatrix}, \quad
\mathbf{y} =
\begin{bmatrix}
22 \\
28 \\
37 \\
45 \\
53
\end{bmatrix}
$$

---

### 2. Метод найменших квадратів

Розв’язуємо:

$$
A \mathbf{x} \approx \mathbf{y}, \quad
\mathbf{x} =
\begin{bmatrix}
k \\
b
\end{bmatrix}
$$

---

### 3. Нормальне рівняння

$$
A^T A \mathbf{x} = A^T \mathbf{y}
$$

---

### 4. Обчислення \(A^T A\)

$$
A^T =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
1 & 1 & 1 & 1 & 1
\end{bmatrix}
$$

$$
A^T A =
\begin{bmatrix}
55 & 15 \\
15 & 5
\end{bmatrix}
$$

---

### 5. Обчислення \(A^T y\)

$$
A^T y =
\begin{bmatrix}
539 \\
185
\end{bmatrix}
$$

---

### 6. Розв’язання системи

$$
\begin{bmatrix}
55 & 15 \\
15 & 5
\end{bmatrix}
\begin{bmatrix}
k \\
b
\end{bmatrix}
=
\begin{bmatrix}
539 \\
185
\end{bmatrix}
$$

Розв’язок:

$$
k \approx 7.7, \quad b \approx 14.3
$$

---

### 7. Рівняння тренду

$$
y \approx 7.7t + 14.3
$$

---

### 8. Прогноз на 6-ту годину

$$
\hat{y} = 7.7 \cdot 6 + 14.3 = 60.5
$$

---

### 9. Висновок

Отримана модель добре описує зростання навантаження:

- Нахил \(k > 0\) → навантаження зростає  
- Прогноз: на 6-ту годину CPU ≈ **60.5%**

In [35]:
import numpy as np

t = np.array([1, 2, 3, 4, 5])
y = np.array([22, 28, 37, 45, 53])

print("t:", t)
print("y:", y)

A = (np.column_stack((t, np.ones(len(t))))).astype(int)

print("Matrix A:")
print(A)

solution, residuals, rank, s = np.linalg.lstsq(A, y)
k, b = solution

print("\nk (slope):", round(k, 3))
print("b (intercept):", round(b, 3))

y_pred_6 = k * 6 + b

print("\nPrediction for t=6:")
print("y =", round(y_pred_6, 3))

print("\nTrend line:")
print(f"y = {round(k,3)} * t + {round(b,3)}")

#bonus

AT = A.T
ATA = AT @ A

print("A^T * A:")
print(ATA)

ATy = AT @ y

print("\nA^T * y:")
print(ATy)

x_manual = np.linalg.solve(ATA, ATy)

k_manual, b_manual = x_manual

print("\nManual solution:")
print("k =", round(k_manual, 3))
print("b =", round(b_manual, 3))

print("\nComparison:")
print("lstsq:", round(k,3), round(b,3))
print("manual:", round(k_manual,3), round(b_manual,3))

t: [1 2 3 4 5]
y: [22 28 37 45 53]
Matrix A:
[[1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]]

k (slope): 7.9
b (intercept): 13.3

Prediction for t=6:
y = 60.7

Trend line:
y = 7.9 * t + 13.3
A^T * A:
[[55 15]
 [15  5]]

A^T * y:
[634 185]

Manual solution:
k = 7.9
b = 13.3

Comparison:
lstsq: 7.9 13.3
manual: 7.9 13.3
